//! Recognizing machine-written files, so a diff can put them where they
//! belong: at the bottom, folded, and labelled.
//!
//! Two signals, used at different times. The path is intrinsic and always
//! available, so it is what orders excerpts before any buffer has loaded. The
//! header comment needs the text, so it only refines the verdict once the
//! buffer is in hand.

use language::BufferSnapshot;
use util::rel_path::RelPath;

/// File names that are wholly tool output.
const GENERATED_FILE_NAMES: &[&str] = &[
    "Cargo.lock",
    "Gemfile.lock",
    "Podfile.lock",
    "bun.lock",
    "bun.lockb",
    "composer.lock",
    "flake.lock",
    "go.sum",
    "package-lock.json",
    "pnpm-lock.yaml",
    "poetry.lock",
    "uv.lock",
    "yarn.lock",
];

/// Suffixes owned by a code generator. Protobuf and its neighbours dominate;
/// `.pyi` is here because a stub file's diff is almost never what a reviewer
/// came to read.
const GENERATED_NAME_SUFFIXES: &[&str] = &[
    ".pb.cc",
    ".pb.go",
    ".pb.h",
    ".pb.py",
    ".pb.rs",
    "_pb2.py",
    "_pb2.pyi",
    "_pb2_grpc.py",
    "_pb.d.ts",
    "_pb.js",
    ".pyi",
    ".freezed.dart",
    ".g.dart",
    ".gr.dart",
    ".designer.cs",
    ".min.css",
    ".min.js",
    ".map",
];

/// Name fragments that say "generated" outright, whatever the extension.
const GENERATED_NAME_FRAGMENTS: &[&str] = &[".generated.", "_generated.", "-generated."];

/// Directory names whose whole contents are output.
const GENERATED_DIRECTORIES: &[&str] = &["__generated__", "generated"];

/// Markers conventionally carried in a generated file's header comment. Matched
/// case-insensitively against the start of the file only, so a passing mention
/// further down does not count.
const GENERATED_TEXT_MARKERS: &[&str] = &[
    "@generated",
    "code generated by",
    "do not edit",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "this file is generated",
    "generated file",
    "generated by the protocol buffer compiler",
];

/// How much of a file's start to search for a generator marker. Generators put
/// theirs in the first line or two; this is generous enough for a license
/// header to sit above it.
const HEADER_SCAN_CHARS: usize = 2048;

pub(crate) fn path_is_generated(path: &RelPath) -> bool {
    let mut components = path.components().peekable();
    let mut file_name = None;
    while let Some(component) = components.next() {
        if components.peek().is_none() {
            file_name = Some(component);
        } else if GENERATED_DIRECTORIES.contains(&component) {
            return true;
        }
    }
    let Some(file_name) = file_name else {
        return false;
    };

    GENERATED_FILE_NAMES.contains(&file_name)
        || GENERATED_NAME_SUFFIXES
            .iter()
            .any(|suffix| file_name.len() > suffix.len() && file_name.ends_with(suffix))
        || GENERATED_NAME_FRAGMENTS
            .iter()
            .any(|fragment| file_name.contains(fragment))
}

pub(crate) fn text_is_generated(text: &str) -> bool {
    let header = match text.char_indices().nth(HEADER_SCAN_CHARS) {
        Some((offset, _)) => &text[..offset],
        None => text,
    }
    .to_ascii_lowercase();
    GENERATED_TEXT_MARKERS
        .iter()
        .any(|marker| header.contains(marker))
}

/// Whether the buffer opens with a generator marker. Says nothing about the
/// path, which callers that have one check for themselves.
pub(crate) fn text_is_generated_header(buffer: &BufferSnapshot) -> bool {
    let header: String = buffer.chars_at(0).take(HEADER_SCAN_CHARS).collect();
    text_is_generated(&header)
}

/// Both signals, for callers holding nothing but the buffer.
pub(crate) fn buffer_is_generated(buffer: &BufferSnapshot) -> bool {
    buffer
        .file()
        .is_some_and(|file| path_is_generated(file.path()))
        || text_is_generated_header(buffer)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated_path(path: &str) -> bool {
        path_is_generated(&RelPath::from_unix_str(path).unwrap())
    }

    #[test]
    fn recognizes_generated_paths() {
        assert!(generated_path("api/service.pb.go"));
        assert!(generated_path("api/service_pb2.py"));
        assert!(generated_path("api/service_pb2.pyi"));
        assert!(generated_path("types/api.pyi"));
        assert!(generated_path("Cargo.lock"));
        assert!(generated_path("web/package-lock.json"));
        assert!(generated_path("web/dist/app.min.js"));
        assert!(generated_path("src/schema.generated.ts"));
        assert!(generated_path("src/__generated__/query.ts"));
        assert!(generated_path("src/generated/query.ts"));

        assert!(!generated_path("src/main.rs"));
        assert!(!generated_path("src/lock.rs"));
        assert!(!generated_path("docs/generated.md"));
        assert!(!generated_path("src/generator/emit.rs"));
    }

    #[test]
    fn a_bare_suffix_is_not_a_file_name() {
        // ".pyi" as the whole name is a dotfile, not a stub for something.
        assert!(!generated_path(".pyi"));
    }

    #[test]
    fn recognizes_generator_headers() {
        assert!(text_is_generated(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n"
        ));
        assert!(text_is_generated("/* @generated */\nexport const x = 1;\n"));
        assert!(text_is_generated(
            "# This file is generated by cargo-about\n"
        ));

        assert!(!text_is_generated("fn main() {}\n"));
        // Far enough down the file to be discussion, not a header.
        let late = format!("fn main() {{}}\n{}\n// @generated\n", "x\n".repeat(2048));
        assert!(!text_is_generated(&late));
    }
}
