//! Recognizing machine-written files, so a diff can sort them last, folded and labelled. The path
//! orders excerpts before buffers load; a header marker refines the verdict once they have.

use language::BufferSnapshot;
use util::rel_path::RelPath;

const GENERATED_FILE_NAMES: &[&str] = &[
    ".terraform.lock.hcl",
    "Cargo.lock",
    "Gemfile.lock",
    "Package.resolved",
    "Pipfile.lock",
    "Podfile.lock",
    "bun.lock",
    "bun.lockb",
    "composer.lock",
    "deno.lock",
    "flake.lock",
    "go.sum",
    "go.work.sum",
    "gradle.lockfile",
    "mix.lock",
    "package-lock.json",
    "packages.lock.json",
    "pnpm-lock.yaml",
    "poetry.lock",
    "pubspec.lock",
    "uv.lock",
    "yarn.lock",
];

const GENERATED_NAME_SUFFIXES: &[&str] = &[
    ".pb.cc",
    ".pb.go",
    ".pb.h",
    ".pb.py",
    ".pb.rs",
    "_pb2.py",
    "_pb2.pyi",
    "_pb2_grpc.py",
    "_pb.d.ts",
    "_pb.js",
    ".pyi",
    ".freezed.dart",
    ".g.dart",
    ".gr.dart",
    ".designer.cs",
    ".min.css",
    ".min.js",
    ".map",
];

const GENERATED_NAME_FRAGMENTS: &[&str] = &[".generated.", "_generated.", "-generated."];

const GENERATED_DIRECTORIES: &[&str] = &["__generated__", "generated"];

/// Matched only near the start of the file, so a passing mention further down doesn't count.
const GENERATED_TEXT_MARKERS: &[&str] = &[
    "@generated",
    "code generated by",
    "do not edit",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "this file is generated",
    "generated file",
    "generated by the protocol buffer compiler",
];

/// Leaves room for a license header above the marker.
const HEADER_SCAN_CHARS: usize = 2048;

pub(crate) fn path_is_generated(path: &RelPath) -> bool {
    let mut components = path.components().peekable();
    let mut file_name = None;
    while let Some(component) = components.next() {
        if components.peek().is_none() {
            file_name = Some(component);
        } else if GENERATED_DIRECTORIES.contains(&component) {
            return true;
        }
    }
    let Some(file_name) = file_name else {
        return false;
    };

    GENERATED_FILE_NAMES.contains(&file_name)
        || GENERATED_NAME_SUFFIXES
            .iter()
            .any(|suffix| file_name.len() > suffix.len() && file_name.ends_with(suffix))
        || GENERATED_NAME_FRAGMENTS
            .iter()
            .any(|fragment| file_name.contains(fragment))
}

pub(crate) fn text_is_generated(text: &str) -> bool {
    let header = match text.char_indices().nth(HEADER_SCAN_CHARS) {
        Some((offset, _)) => &text[..offset],
        None => text,
    }
    .to_ascii_lowercase();
    GENERATED_TEXT_MARKERS
        .iter()
        .any(|marker| header.contains(marker))
}

pub(crate) fn text_is_generated_header(buffer: &BufferSnapshot) -> bool {
    let header: String = buffer.chars_at(0).take(HEADER_SCAN_CHARS).collect();
    text_is_generated(&header)
}

pub(crate) fn buffer_is_generated(buffer: &BufferSnapshot) -> bool {
    buffer
        .file()
        .is_some_and(|file| path_is_generated(file.path()))
        || text_is_generated_header(buffer)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated_path(path: &str) -> bool {
        path_is_generated(&RelPath::from_unix_str(path).unwrap())
    }

    #[test]
    fn recognizes_generated_paths() {
        assert!(generated_path("api/service.pb.go"));
        assert!(generated_path("api/service_pb2.py"));
        assert!(generated_path("api/service_pb2.pyi"));
        assert!(generated_path("types/api.pyi"));
        assert!(generated_path("Cargo.lock"));
        assert!(generated_path("web/package-lock.json"));
        assert!(generated_path("Pipfile.lock"));
        assert!(generated_path("app/pubspec.lock"));
        assert!(generated_path("go.work.sum"));
        assert!(generated_path("web/deno.lock"));
        assert!(generated_path("ios/Package.resolved"));
        assert!(generated_path("infra/.terraform.lock.hcl"));
        assert!(generated_path("android/gradle.lockfile"));
        assert!(generated_path("src/packages.lock.json"));
        assert!(generated_path("mix.lock"));
        assert!(generated_path("web/dist/app.min.js"));
        assert!(generated_path("src/schema.generated.ts"));
        assert!(generated_path("src/__generated__/query.ts"));
        assert!(generated_path("src/generated/query.ts"));

        assert!(!generated_path("src/main.rs"));
        assert!(!generated_path("src/lock.rs"));
        assert!(!generated_path("docs/generated.md"));
        assert!(!generated_path("src/generator/emit.rs"));
    }

    #[test]
    fn a_bare_suffix_is_not_a_file_name() {
        assert!(!generated_path(".pyi"));
    }

    #[test]
    fn recognizes_generator_headers() {
        assert!(text_is_generated(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n"
        ));
        assert!(text_is_generated("/* @generated */\nexport const x = 1;\n"));
        assert!(text_is_generated(
            "# This file is generated by cargo-about\n"
        ));

        assert!(!text_is_generated("fn main() {}\n"));
        let late = format!("fn main() {{}}\n{}\n// @generated\n", "x\n".repeat(2048));
        assert!(!text_is_generated(&late));
    }
}
